services:
  - type: web
    name: pukpik
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /index.html
        name: Cache-Control
        value: no-cache
